/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PapersImport } from './routes/papers'
import { Route as AboutImport } from './routes/about'

// Create/Update Routes

const PapersRoute = PapersImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/papers': typeof PapersRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/papers': typeof PapersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutRoute
  '/papers': typeof PapersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/papers'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/papers'
  id: '__root__' | '/about' | '/papers'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  PapersRoute: typeof PapersRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  PapersRoute: PapersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/papers"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/papers": {
      "filePath": "papers.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
